substitutions:
  initial_value: 5
  min_value: 0
  max_value: 10

packages:
  - !include ./packages/matouch-esp32-s3-rotary-ips-display-st7701.yaml

esphome:
  name: demo-st7701
  friendly_name: MaTouch ESP32-S3 Rotary IPS Display with Touch 2.1“ ST7701

# Enable logging
logger:
  level: DEBUG

binary_sensor:
  # Copy of the button binary sensor to add on_press handlder and use encoder button as enter button
  - platform: copy
    id: matouch_button_copy
    source_id: matouch_button
    internal: true
    on_press:
      - lvgl.page.next:
          animation: FADE_OUT
          time: 80ms

number:
  - platform: template
    id: arc_value
    internal: true
    min_value: ${min_value}
    max_value: ${max_value}
    step: 1
    initial_value: ${initial_value}
    optimistic: true
    on_value:
      then:
        - lvgl.arc.update:
            id: second_screen_arc
            value: !lambda 'return x;'

sensor:
  - platform: copy
    source_id: matouch_encoder
    id: matouch_encoder_copy
    internal: true
    on_value:
      then:
        - lambda: |-
            static int last = 0;
            int delta = (int)x - last;
            last = (int)x;

            auto v = id(arc_value).state + delta;
            if (v < ${min_value}) v = ${min_value};
            if (v > ${max_value}) v = ${max_value};

            ESP_LOGD("encoder", "raw=%d delta=%d v=%d", (int)x, delta, (int)v);

            id(arc_value).publish_state(v);

lvgl:
  update_interval: 33ms
  buffer_size: 100%
  touchscreens:
    - touchscreen_id : matouch_touchscreen
  pages:
    - id: first_screen
      text_color: white
      bg_color: black
      widgets:
        - label:
            align: CENTER
            text_font: montserrat_30
            text: 'Press me'
    - id: second_screen
      text_color: white
      bg_color: black
      widgets:
        - arc:
            id: second_screen_arc
            x: 0
            y: 0
            align: CENTER
            width: 460
            height: 460
            min_value: ${min_value}
            max_value: ${max_value}
            value: ${initial_value}
            adjustable: true
            start_angle: 130
            end_angle: 50
            arc_width: 40
            arc_color: 0x111111
            arc_rounded: true
            indicator:
              arc_width: 40
              arc_rounded: true
              arc_opa: 100%
              arc_color: red
            knob:
              bg_color: white
            on_value:
              - logger.log:
                  level: INFO
                  format: "Setting value to %.0f"
                  args: [ 'x' ]
              - lvgl.label.update:
                  id: second_screen_value_label
                  text: !lambda 'return std::to_string((int)x);'
        - label:
            id: second_screen_value_label
            align: CENTER
            y: 0
            text_font: montserrat_48
            text: "${initial_value}"
            text_color: white