# -----------------------------------------------------------------------------
# matouch esp32-s3 rotary ips display with touch 2.1 st7701
#
# https://wiki.makerfabs.com/MaTouch_ESP32_S3_2.1_Rotary_TFT_with_Touch.html
#
# This package configures the MaTouch ESP32-S3 Rotary IPS Display with Touch 2.1"
# using the ST7701S display driver and CST826 touch controller.
#
# Hardware:
#   - Board: ESP32-S3
#   - Display: 2.1" IPS Round (480x480)
#   - Driver: ST7701S (RGB Interface)
#   - Touch: CST826 (I2C)
#   - Input: Rotary Encoder + Button
# -----------------------------------------------------------------------------

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

substitutions:
  # I2C Pins
  I2C_SDA_PIN: "17"
  I2C_SCL_PIN: "18"

  # Touch Screen Pins
  TOUCH_I2C_ADDR: "0x15"

  # Display Backlight
  TFT_BL: "38"

  # RGB Panel Control
  RGB_PIN_DE: "2"
  RGB_PIN_VSYNC: "42"
  RGB_PIN_HSYNC: "3"
  RGB_PIN_PCLK: "45"

  # RGB Red Channel
  RGB_PIN_R0: "4"
  RGB_PIN_R1: "41"
  RGB_PIN_R2: "5"
  RGB_PIN_R3: "40"
  RGB_PIN_R4: "6"

  # RGB Green Channel
  RGB_PIN_G0: "39"
  RGB_PIN_G1: "7"
  RGB_PIN_G2: "47"
  RGB_PIN_G3: "8"
  RGB_PIN_G4: "48"
  RGB_PIN_G5: "9"

  # RGB Blue Channel
  RGB_PIN_B0: "11"
  RGB_PIN_B1: "15"
  RGB_PIN_B2: "12"
  RGB_PIN_B3: "16"
  RGB_PIN_B4: "21"

  # SPI Pins
  SPI_CS: "1"
  SPI_SCK: "46"
  SPI_MOSI: "0"

  # User Input Pins
  BUTTON_PIN: "14"
  ENCODER_CLK: "13"
  ENCODER_DT: "10"

  # Display Configuration
  SCREEN_WIDTH: "480"
  SCREEN_HEIGHT: "480"

  # RGB Panel Timing
  RGB_HSYNC_POLARITY: "1"
  RGB_HSYNC_FRONT_PORCH: "10"
  RGB_HSYNC_PULSE_WIDTH: "8"
  RGB_HSYNC_BACK_PORCH: "50"

  RGB_VSYNC_POLARITY: "1"
  RGB_VSYNC_FRONT_PORCH: "10"
  RGB_VSYNC_PULSE_WIDTH: "8"
  RGB_VSYNC_BACK_PORCH: "20"

# please add the following to your esphome section to forces the build system
# to generate a Bootloader specifically for "Quad Flash + Octal PSRAM" (qio_opi).
#
# esphome:
#   platformio_options:
#     board_build.f_cpu: 240000000L          # Force CPU to 240MHz
#     board_build.flash_mode: qio            # Quad I/O for Flash
#     board_build.f_flash: 80000000L         # Flash speed 80MHz
#     board_build.arduino.memory_type: qio_opi # Enable Octal Mode for PSRAM (Fastest)
#
psram:
  mode: octal
  speed: 80MHz

spi:
  clk_pin:
    number: ${SPI_SCK}
    # supress the warning "...is a strapping PIN and should only be used for I/O with care"
    ignore_strapping_warning: true
  mosi_pin:
    number: ${SPI_MOSI}
    # supress the warning "...is a strapping PIN and should only be used for I/O with care"
    ignore_strapping_warning: true

output:
  - platform: gpio
    pin: ${TFT_BL}
    id: matouch_backlight_pwm

light:
  - platform: binary
    output: matouch_backlight_pwm
    name: "Display Backlight"
    id: matouch_backlight
    restore_mode: ALWAYS_ON

display:
  - platform: mipi_rgb
    model: custom
    id: matouch_display
    color_order: BGR
    pclk_frequency: 16MHz
    pixel_mode: 18bit
    dimensions:
      width: 480
      height: 480
    de_pin:
      number: ${RGB_PIN_DE}
    hsync_pin:
      number: ${RGB_PIN_HSYNC}
      ignore_strapping_warning: true
    vsync_pin: ${RGB_PIN_VSYNC}
    pclk_pin:
      number: ${RGB_PIN_PCLK}
      ignore_strapping_warning: true
    pclk_inverted: false
    hsync_back_porch: ${RGB_HSYNC_BACK_PORCH}
    hsync_front_porch: ${RGB_HSYNC_FRONT_PORCH}
    hsync_pulse_width: ${RGB_HSYNC_PULSE_WIDTH}
    vsync_back_porch: ${RGB_VSYNC_BACK_PORCH}
    vsync_front_porch: ${RGB_VSYNC_FRONT_PORCH}
    vsync_pulse_width: ${RGB_VSYNC_PULSE_WIDTH}
    data_pins:
      red:
        - ${RGB_PIN_R0}
        - ${RGB_PIN_R1}
        - ${RGB_PIN_R2}
        - ${RGB_PIN_R3}
        - ${RGB_PIN_R4}
      green:
        - ${RGB_PIN_G0}
        - ${RGB_PIN_G1}
        - ${RGB_PIN_G2}
        - ${RGB_PIN_G3}
        - ${RGB_PIN_G4}
        - ${RGB_PIN_G5}
      blue:
        - ${RGB_PIN_B0}
        - ${RGB_PIN_B1}
        - ${RGB_PIN_B2}
        - ${RGB_PIN_B3}
        - ${RGB_PIN_B4}
    # st7701s type5 based on Arduino_GFX implementation
    # https://github.com/moononournation/Arduino_GFX/blob/master/src/display/Arduino_RGB_Display.h#L2465
    init_sequence:
      - [0xFF, 0x77, 0x01, 0x00, 0x00, 0x10]
      - [0xC0, 0x3B, 0x00]
      - [0xC1, 0x0B, 0x02]
      - [0xC2, 0x00, 0x02]
      - [0xCC, 0x10]
      - [0xCD, 0x08]
      - [0xB0, 0x02, 0x13, 0x1B, 0x0D, 0x10, 0x05, 0x08, 0x07, 0x07, 0x24, 0x04, 0x11, 0x0E, 0x2C, 0x33, 0x1D]
      - [0xB1, 0x05, 0x13, 0x1B, 0x0D, 0x11, 0x05, 0x08, 0x07, 0x07, 0x24, 0x04, 0x11, 0x0E, 0x2C, 0x33, 0x1D]
      - [0xFF, 0x77, 0x01, 0x00, 0x00, 0x11]
      - [0xB0, 0x5d]
      - [0xB1, 0x43]
      - [0xB2, 0x81]
      - [0xB3, 0x80]
      - [0xB5, 0x43]
      - [0xB7, 0x85]
      - [0xB8, 0x20]
      - [0xC1, 0x78]
      - [0xC2, 0x78]
      - [0xD0, 0x88]
      - [0xE0, 0x00, 0x00, 0x02]
      - [0xE1, 0x03, 0xA0, 0x00, 0x00, 0x04, 0xA0, 0x00, 0x00, 0x00, 0x20, 0x20]
      - [0xE2, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
      - [0xE3, 0x00, 0x00, 0x11, 0x00]
      - [0xE4, 0x22, 0x00]
      - [0xE5, 0x05, 0xEC, 0xA0, 0xA0, 0x07, 0xEE, 0xA0, 0xA0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
      - [0xE6, 0x00, 0x00, 0x11, 0x00]
      - [0xE7, 0x22, 0x00]
      - [0xE8, 0x06, 0xED, 0xA0, 0xA0, 0x08, 0xEF, 0xA0, 0xA0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
      - [0xEB, 0x00, 0x00, 0x40, 0x40, 0x00, 0x00, 0x00]
      - [0xED, 0xFF, 0xFF, 0xFF, 0xBA, 0x0A, 0xBF, 0x45, 0xFF, 0xFF, 0x54, 0xFB, 0xA0, 0xAB, 0xFF, 0xFF, 0xFF]
      - [0xEF, 0x10, 0x0D, 0x04, 0x08, 0x3F, 0x1F]
      - [0xFF, 0x77, 0x01, 0x00, 0x00, 0x13]
      - [0xEF, 0x08]
      - [0xFF, 0x77, 0x01, 0x00, 0x00, 0x00]
      # MADCTL command code is not the right one in https://github.com/esphome/esphome/blob/dev/esphome/components/mipi_rgb/models/st7701s.py#L11
      # transform.mirror_y  and color_order might not be applied correctly
      - [0x36, 0x08] # MADCTL:  0x00 RGB mode, | 0x08 BGR mode | 0x10 mirror Y
      - [0x3A, 0x60] # COLMOD: 0x70 RGB888, 0x60 RGB666, 0x50 RGB565
      # a 200 ms delay is added automatically before Sleep Out
      - [0x11] # Sleep Out
      # a 10ms after Sleep Out
      # - delay 100ms
      - [0x29] # Display On
      # a 10ms delay is added automatically at the end
      # - [0x32, 0xFF] # delay 50ms

    update_interval: never
    auto_clear_enabled: false

    # show_test_card: true

binary_sensor:
  - platform: gpio
    id: matouch_button
    name: "Button"
    pin:
      number: ${BUTTON_PIN}
      mode:
        input: true
        pullup: true
      inverted: true

sensor:
  - platform: rotary_encoder
    id: matouch_encoder
    name: "Rotary Encoder"
    pin_a:
      number: ${ENCODER_CLK}
      mode:
        input: true
        pullup: true
    pin_b:
      number: ${ENCODER_DT}
      mode:
        input: true
        pullup: true

i2c:
  id: bus_a
  sda: ${I2C_SDA_PIN}
  scl: ${I2C_SCL_PIN}
  # scan: true

touchscreen:
  id: matouch_touchscreen
  platform: cst816
  update_interval: 50ms
  i2c_id: bus_a
  address: ${TOUCH_I2C_ADDR}
